---
name: Main
on: [push, pull_request]

jobs:
  should-run:
    name: Should run
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    outputs:
      should-run: ${{ steps.action.outputs.should-run }}
    steps:
      - id: action
        uses: techneg-it/should-workflow-run@eff19348eb884f57e05bc6f05ae48ece3af14714 # v1.0.1
  pre-commit:
    name: Run `pre-commit`
    needs: should-run
    if: fromJSON(needs.should-run.outputs.should-run)
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    env:
      # renovate: datasource=custom.python-versions depName=actions/python-versions versioning=pep440
      PYTHON_VERSION: 3.13.7
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
  gv:
    name: Get value
    needs: should-run
    if: fromJSON(needs.should-run.outputs.should-run)
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    outputs:
      value: ${{ steps.get-value.outputs.value }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - id: get-value
        name: Run this action
        uses: ./
      - run: |
          echo "::notice ::Value: ${{ steps.get-value.outputs.value }}"
  show-value:
    name: Show value
    needs:
      - gv
      - should-run
    if: fromJSON(needs.should-run.outputs.should-run)
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - run: |
          echo "::notice ::Value: $VALUE"
        env:
          VALUE: ${{ fromJSON(needs.gv.outputs.value) }}
  results:
    name: Collect results
    permissions:
      checks: read
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: poseidon/wait-for-status-checks@899c768d191b56eef585c18f8558da19e1f3e707 # v0.6.0
        with:
          ignore: Collect results
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Run `semantic-release`
        uses: codfish/semantic-release-action@22ce451ffd02a9ee2c4bfd126d028e4bd655770e # v4.0.0
        id: sem-rel
        with:
          plugins: |
            [ "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator",
              "@semantic-release/github"
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update branch for major version
        if: steps.sem-rel.outputs.new-release-published == 'true'
        run: git push
             https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
             HEAD:refs/heads/v${{steps.sem-rel.outputs.release-major}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
